### PR TITLE
Add `add_many()` method to Collection.

### PR DESCRIPTION
**Pull request by shazahm1**
gh-14

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
Looks good, but the .gitignore change shouldn't be in here.

**Comment by shazahm1** [comment]
K, I'll remove it... I think it was accidently included when a was making issue branches.

**Comment by shazahm1** [comment]
Would you like a unit test for this? I'm thinking simply adding another case in `test-has-many.php` similar to `test_has_many()`.

**Comment by TimothyBJacobs** [comment]
Sure. But I'd add it in `tests/unit/test-collection.php`

**Comment by shazahm1** [comment]
Ahh, yes, that makes sense. Working on it now.

**Pull request merged**
