### PR TITLE
Add support to Manager to drop a table if it exists.

### PR DESCRIPTION
**Pull request by shazahm1**
gh-21

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
Hm, is there a reason why the `Table` interface needs to provide the SQL for dropping or truncating as opposed to the `Manager` class itself?

**Comment by shazahm1** [comment]
The `Table` interface defines a method for the creation sql, so, I matched the creation assuming that is what you would want in order for this to get merged.

**Comment by TimothyBJacobs** [comment]
I think we should put it in the Manager class as it would be the same for every table right?

**Comment by shazahm1** [comment]
Alrighty, I'll rework it and update the PR.

**Comment by shazahm1** [comment]
I've updated the PR. The code is all in `Manager` now. If it looks goo. I'll update with unit tests.

**Comment by TimothyBJacobs** [comment]
Yep, looks good!

**Comment by shazahm1** [comment]
Unit test should go in test-manager, correct?

**Comment by shazahm1** [comment]
I'm working on learning/writing the unit tests for these... Several of the tests in `test-manager.php` do not have asserts. Is that correct?

**Comment by TimothyBJacobs** [comment]
Those tests are using mocks. PHPUnit will mark the test as failed when the method completes if the expects() calls aren't fulfilled. https://phpunit.de/manual/4.8/en/test-doubles.html

**Comment by shazahm1** [comment]
Ok, have unit tests added. It took a few stabs but I think I have and understand what they are doing and what they are actually testing. I do need to figure out how to get these to run locally though. Project for today :)

**Pull request merged**
